//! Go's own function table, `.gopclntab`, which the runtime reads for its
//! tracebacks and which survives stripping.
//!
//! The table's layout is keyed by its magic number: only the format Go 1.20
//! through 1.27 write (`0xfffffff1`) is read, and every other magic is
//! refused with the releases that wrote it. Function IDs are numbered
//! differently across those releases, so they are interpreted only for the
//! releases whose numbering is written down here, by the Go version the
//! image records. Every read is bounded, and a malformed table is a typed
//! error, never a guess.

mod metadata;
mod unwind;

pub use metadata::{Catalog, complete as complete_metadata};
pub use unwind::{GoUnwind, frame_saves};

use crate::image::unwind::GoTableFacts;
use std::ops::Range;
use std::sync::Arc;

/// The magic number of the table Go 1.20 through 1.27 write.
const GO120_MAGIC: u32 = 0xffff_fff1;

/// The size of the table header: the magic, two pad bytes, the instruction
/// size quantum, the pointer size, and eight pointer-sized words.
const HEADER_SIZE: usize = 8 + 8 * 8;

/// The fixed part of one function's `_func` record, before its `pcdata`
/// and `funcdata` offsets.
const FUNC_SIZE: usize = 44;

/// The size of one inline-tree entry, an `inlinedCall`.
const INLINED_CALL_SIZE: usize = 16;

/// `PCDATA_InlTreeIndex`, the pc-value table giving the inline-tree entry
/// at each instruction.
const PCDATA_INLINE_TREE_INDEX: usize = 2;

/// `FUNCDATA_InlTree`, the offset of a function's inline tree from
/// `go:func.*`.
const FUNCDATA_INLINE_TREE: usize = 3;

/// `abi.FuncFlagTopFrame`: the function is the outermost frame of a stack.
const FLAG_TOP_FRAME: u8 = 1 << 0;
/// `abi.FuncFlagSPWrite`: the function writes SP other than by a constant.
const FLAG_SP_WRITE: u8 = 1 << 1;
/// `abi.FuncFlagAsm`: the function is written in assembly.
const FLAG_ASM: u8 = 1 << 2;

/// The longest pc-value delta a well-formed table encodes, in varint bytes.
const MAX_VARINT_BYTES: usize = 5;

/// Why a Go function table cannot be read.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum PclntabError {
    #[error("the Go function table is truncated: {0}")]
    Truncated(&'static str),
    #[error("the Go function table was written by {0}, whose format is not supported")]
    UnsupportedRelease(&'static str),
    #[error("the Go function table's magic number {0:#010x} is unknown")]
    UnknownMagic(u32),
    #[error("the Go function table is malformed: {0}")]
    Malformed(Arc<str>),
    #[error("the Go function table's code addresses are relative to an unknown text start")]
    TextStartUnknown,
}

type Result<T> = std::result::Result<T, PclntabError>;

fn malformed(reason: impl Into<Arc<str>>) -> PclntabError {
    PclntabError::Malformed(reason.into())
}

/// A function the runtime treats specially, by its function ID.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SpecialFunction {
    Abort,
    AsmCgoCall,
    AsyncPreempt,
    CgoCallback,
    CoroStart,
    DebugCallV2,
    GcBgMarkWorker,
    Goexit,
    Gogo,
    Gopanic,
    HandleAsyncEvent,
    Mcall,
    Morestack,
    Mstart,
    Panicwrap,
    Rt0Go,
    RuntimeMain,
    RunFinalizers,
    RunCleanups,
    Sigpanic,
    Systemstack,
    SystemstackSwitch,
    /// Autogenerated code: ABI and method wrappers, hash and equality
    /// algorithms, and the like.
    Wrapper,
}

/// How a release numbers its function IDs (`internal/abi.FuncID`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum FuncIdNumbering {
    /// Go 1.25 through 1.27, which added `runFinalizers` and `runCleanups`
    /// in place of `runfinq`.
    Go125,
}

impl FuncIdNumbering {
    /// The numbering of a release, for the releases written down here.
    const fn of(release: GoRelease) -> Option<Self> {
        match release {
            GoRelease {
                major: 1,
                minor: 25..=27,
            } => Some(Self::Go125),
            _ => None,
        }
    }

    const fn special(self, id: u8) -> Option<SpecialFunction> {
        use SpecialFunction as S;
        match self {
            Self::Go125 => Some(match id {
                1 => S::Abort,
                2 => S::AsmCgoCall,
                3 => S::AsyncPreempt,
                4 => S::CgoCallback,
                5 => S::CoroStart,
                6 => S::DebugCallV2,
                7 => S::GcBgMarkWorker,
                8 => S::Goexit,
                9 => S::Gogo,
                10 => S::Gopanic,
                11 => S::HandleAsyncEvent,
                12 => S::Mcall,
                13 => S::Morestack,
                14 => S::Mstart,
                15 => S::Panicwrap,
                16 => S::Rt0Go,
                17 => S::RuntimeMain,
                18 => S::RunFinalizers,
                19 => S::RunCleanups,
                20 => S::Sigpanic,
                21 => S::Systemstack,
                22 => S::SystemstackSwitch,
                23 => S::Wrapper,
                _ => return None,
            }),
        }
    }
}

/// A Go release, as `runtime.buildVersion` names it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct GoRelease {
    pub major: u32,
    pub minor: u32,
}

impl GoRelease {
    /// Parses a version such as `go1.27.1` or `go1.27rc1`; a development
    /// build names no release.
    fn parse(version: &str) -> Option<Self> {
        let rest = version.strip_prefix("go")?;
        let mut parts = rest.split('.');
        let major = parts.next()?.parse().ok()?;
        let minor = parts.next()?;
        let digits = minor
            .find(|character: char| !character.is_ascii_digit())
            .unwrap_or(minor.len());
        Some(Self {
            major,
            minor: minor[..digits].parse().ok()?,
        })
    }
}

/// What the table records about one function, besides its tables.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct GoFunctionFacts {
    /// The runtime's special treatment of the function, when the image's
    /// release numbers function IDs in a way written down here.
    pub special: Option<SpecialFunction>,
    /// The function is the outermost frame of its stack (`TOPFRAME`).
    pub top_frame: bool,
    /// The function writes SP other than by a constant (`SPWRITE`).
    pub sp_write: bool,
    /// The function is written in assembly (`ASM`).
    pub assembly: bool,
}

/// One function of the table. Addresses are image addresses.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GoFunction {
    pub entry: u64,
    /// The first address past the function, where the next one begins.
    pub end: u64,
    pub facts: GoFunctionFacts,
    /// The line of its `func` keyword or `TEXT` directive.
    pub start_line: i32,
    name: u32,
    pcsp: u32,
    pcfile: u32,
    pcln: u32,
    cu_offset: u32,
    /// Where the `pcdata` offsets begin, in the table.
    pcdata: usize,
    npcdata: u32,
    nfuncdata: u8,
}

impl GoFunction {
    /// Whether the function's code was compiled by Go: it has a stack
    /// table. Code the linker took from C objects has none.
    pub const fn is_go(&self) -> bool {
        self.pcsp != 0
    }

    pub const fn contains(&self, address: u64) -> bool {
        self.entry <= address && address < self.end
    }
}

/// One entry of a function's inline tree: a call the compiler inlined.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InlinedCall {
    pub special: Option<SpecialFunction>,
    name: u32,
    /// The address of an instruction whose position is the call site.
    pub parent_pc: u64,
    /// The line of the inlined function's `func` keyword.
    pub start_line: i32,
}

/// One run of a pc-value table: `value` applies to `[start, end)`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PcRun {
    pub start: u64,
    pub end: u64,
    pub value: i32,
}

/// A source position, as the table records it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GoPosition {
    pub file: Arc<str>,
    pub line: i32,
}

/// A parsed Go function table.
#[derive(Debug)]
pub struct GoTable {
    data: Arc<[u8]>,
    quantum: u32,
    funcnametab: Range<usize>,
    cutab: Range<usize>,
    filetab: Range<usize>,
    pctab: Range<usize>,
    pclntable: Range<usize>,
    /// The offset in the table of `go:func.*`, which function data offsets
    /// are relative to, when it was found.
    gofunc: Option<usize>,
    numbering: Option<FuncIdNumbering>,
    functions: Vec<GoFunction>,
    /// What the table was parsed with, which reparses it.
    facts: GoTableFacts,
}

fn read_u32(data: &[u8], offset: usize) -> Option<u32> {
    let bytes = data.get(offset..offset.checked_add(4)?)?;
    Some(u32::from_le_bytes(bytes.try_into().ok()?))
}

fn read_u64(data: &[u8], offset: usize) -> Option<u64> {
    let bytes = data.get(offset..offset.checked_add(8)?)?;
    Some(u64::from_le_bytes(bytes.try_into().ok()?))
}

/// Reads one unsigned LEB128 varint of at most 32 bits.
fn read_varint(data: &[u8], offset: &mut usize) -> Result<u32> {
    let mut value = 0_u32;
    for index in 0..MAX_VARINT_BYTES {
        let byte = *data
            .get(*offset)
            .ok_or(PclntabError::Truncated("a pc-value table"))?;
        *offset += 1;
        let bits = u32::from(byte & 0x7f);
        let shift = 7 * u32::try_from(index).expect("varint index fits u32");
        if shift == 28 && bits > 0xf {
            return Err(malformed("a pc-value delta exceeds 32 bits"));
        }
        value |= bits << shift;
        if byte & 0x80 == 0 {
            return Ok(value);
        }
    }
    Err(malformed("a pc-value delta exceeds 32 bits"))
}

/// The runs of one pc-value table, decoded as `runtime.pcvalue` does: a
/// value starts at -1 and each step adds a zig-zag delta, then advances the
/// pc. A zero delta ends the table, except on the step at the entry.
#[derive(Debug, Clone)]
pub struct PcRuns<'a> {
    data: &'a [u8],
    offset: usize,
    pc: u64,
    entry: u64,
    value: i32,
    quantum: u32,
    done: bool,
}

impl Iterator for PcRuns<'_> {
    type Item = Result<PcRun>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.done {
            return None;
        }
        let step = self.step();
        if !matches!(step, Ok(Some(_))) {
            self.done = true;
        }
        step.transpose()
    }
}

impl PcRuns<'_> {
    fn step(&mut self) -> Result<Option<PcRun>> {
        let delta = read_varint(self.data, &mut self.offset)?;
        if delta == 0 && self.pc != self.entry {
            return Ok(None);
        }
        let delta = if delta & 1 == 0 {
            (delta >> 1).cast_signed()
        } else {
            (!(delta >> 1)).cast_signed()
        };
        let pc_delta = read_varint(self.data, &mut self.offset)?
            .checked_mul(self.quantum)
            .ok_or_else(|| malformed("a pc-value table's pc overflows"))?;
        let start = self.pc;
        self.pc = start
            .checked_add(u64::from(pc_delta))
            .ok_or_else(|| malformed("a pc-value table's pc overflows"))?;
        self.value = self
            .value
            .checked_add(delta)
            .ok_or_else(|| malformed("a pc-value table's value overflows"))?;
        Ok(Some(PcRun {
            start,
            end: self.pc,
            value: self.value,
        }))
    }
}

impl GoTable {
    /// Parses a table whose header is at image address `address`, for code
    /// whose function offsets are relative to `text`. `gofunc` is the image
    /// address of `go:func.*`, when known, and `release` the Go release that
    /// built the image.
    pub fn parse(
        data: Arc<[u8]>,
        address: u64,
        text: u64,
        gofunc: Option<u64>,
        release: Option<GoRelease>,
    ) -> Result<Self> {
        check_magic(&data)?;
        if data.len() < HEADER_SIZE {
            return Err(PclntabError::Truncated("the header"));
        }
        let quantum = u32::from(data[6]);
        if data[4] != 0 || data[5] != 0 || !matches!(quantum, 1 | 2 | 4) {
            return Err(malformed(
                "the header's padding or instruction size is invalid",
            ));
        }
        if data[7] != 8 {
            return Err(PclntabError::UnsupportedRelease(
                "a toolchain for 32-bit pointers",
            ));
        }
        let word = |index: usize| {
            read_u64(&data, 8 + 8 * index)
                .and_then(|value| usize::try_from(value).ok())
                .ok_or(PclntabError::Truncated("the header"))
        };
        let nfunc = word(0)?;
        // Each table follows the previous one, in this order.
        let offsets = [word(3)?, word(4)?, word(5)?, word(6)?, word(7)?, data.len()];
        if offsets[0] < HEADER_SIZE || offsets.windows(2).any(|pair| pair[0] > pair[1]) {
            return Err(malformed("the header's table offsets are out of order"));
        }
        let facts = GoTableFacts {
            address,
            text,
            go_func: gofunc,
            release: release.map(|release| (release.major, release.minor)),
        };
        let mut table = Self {
            facts,
            quantum,
            funcnametab: offsets[0]..offsets[1],
            cutab: offsets[1]..offsets[2],
            filetab: offsets[2]..offsets[3],
            pctab: offsets[3]..offsets[4],
            pclntable: offsets[4]..offsets[5],
            gofunc: gofunc
                .and_then(|gofunc| gofunc.checked_sub(address))
                .and_then(|offset| usize::try_from(offset).ok())
                .filter(|offset| *offset < data.len()),
            numbering: release.and_then(FuncIdNumbering::of),
            functions: Vec::new(),
            data,
        };
        table.functions = table.decode_functions(nfunc, text)?;
        Ok(table)
    }

    /// Decodes the function table: `nfunc` pairs of a text offset and a
    /// `_func` offset, then the offset where the last function ends.
    fn decode_functions(&self, nfunc: usize, text: u64) -> Result<Vec<GoFunction>> {
        let pclntable = &self.data[self.pclntable.clone()];
        if nfunc
            .checked_mul(8)
            .and_then(|size| size.checked_add(4))
            .is_none_or(|size| size > pclntable.len())
        {
            return Err(PclntabError::Truncated("the function table"));
        }
        let entry = |index: usize| -> Result<u64> {
            let offset = read_u32(pclntable, 8 * index)
                .ok_or(PclntabError::Truncated("the function table"))?;
            text.checked_add(u64::from(offset))
                .ok_or_else(|| malformed("a function's address overflows"))
        };
        let mut functions = Vec::with_capacity(nfunc);
        let mut next = if nfunc == 0 { None } else { Some(entry(0)?) };
        for index in 0..nfunc {
            let start = next.expect("a function follows");
            let end = entry(index + 1)?;
            next = Some(end);
            if end < start {
                return Err(malformed("the function table is not sorted by address"));
            }
            let record = read_u32(pclntable, 8 * index + 4)
                .and_then(|offset| usize::try_from(offset).ok())
                .ok_or(PclntabError::Truncated("the function table"))?;
            functions.push(self.decode_function(pclntable, record, start, end, text)?);
        }
        Ok(functions)
    }

    fn decode_function(
        &self,
        pclntable: &[u8],
        record: usize,
        entry: u64,
        end: u64,
        text: u64,
    ) -> Result<GoFunction> {
        let fixed = record
            .checked_add(FUNC_SIZE)
            .and_then(|end| pclntable.get(record..end))
            .ok_or(PclntabError::Truncated("a function record"))?;
        let field = |index: usize| read_u32(fixed, 4 * index).expect("the record is in bounds");
        if text.checked_add(u64::from(field(0))) != Some(entry) {
            return Err(malformed(
                "a function record's entry differs from the function table's",
            ));
        }
        let npcdata = field(7);
        let nfuncdata = fixed[43];
        let trailing = usize::try_from(npcdata)
            .ok()
            .and_then(|npcdata| npcdata.checked_add(usize::from(nfuncdata)))
            .and_then(|count| count.checked_mul(4))
            .ok_or(PclntabError::Truncated("a function record"))?;
        let pcdata = self.pclntable.start + record + FUNC_SIZE;
        if pcdata
            .checked_add(trailing)
            .is_none_or(|end| end > self.pclntable.end)
        {
            return Err(PclntabError::Truncated("a function record"));
        }
        let name = field(1);
        if usize::try_from(name).map_or(true, |name| name >= self.funcnametab.len()) {
            return Err(malformed("a function's name is outside the name table"));
        }
        let flags = fixed[41];
        Ok(GoFunction {
            entry,
            end,
            facts: GoFunctionFacts {
                special: self
                    .numbering
                    .and_then(|numbering| numbering.special(fixed[40])),
                top_frame: flags & FLAG_TOP_FRAME != 0,
                sp_write: flags & FLAG_SP_WRITE != 0,
                assembly: flags & FLAG_ASM != 0,
            },
            start_line: field(9).cast_signed(),
            name,
            pcsp: field(4),
            pcfile: field(5),
            pcln: field(6),
            cu_offset: field(8),
            pcdata,
            npcdata,
            nfuncdata,
        })
    }

    /// Parses a table an image keeps, as [`Self::parse`] did.
    pub fn reparse(data: Arc<[u8]>, facts: GoTableFacts) -> Result<Self> {
        Self::parse(
            data,
            facts.address,
            facts.text,
            facts.go_func,
            facts
                .release
                .map(|(major, minor)| GoRelease { major, minor }),
        )
    }

    /// The table's bytes and what parsing them needs.
    pub const fn source(&self) -> (&Arc<[u8]>, GoTableFacts) {
        (&self.data, self.facts)
    }

    /// Every function, in address order.
    pub fn functions(&self) -> &[GoFunction] {
        &self.functions
    }

    /// The function whose code contains an image address.
    pub fn function_containing(&self, address: u64) -> Option<&GoFunction> {
        let after = self
            .functions
            .partition_point(|function| function.entry <= address);
        self.functions[..after]
            .last()
            .filter(|function| function.contains(address))
    }

    /// A NUL-terminated string at `offset` within `table`.
    fn string(&self, table: &Range<usize>, offset: usize) -> Result<Arc<str>> {
        let bytes = self.data[table.clone()]
            .get(offset..)
            .ok_or_else(|| malformed("a string is outside its table"))?;
        let length = bytes
            .iter()
            .position(|byte| *byte == 0)
            .ok_or(PclntabError::Truncated("a string"))?;
        Ok(String::from_utf8_lossy(&bytes[..length]).into())
    }

    /// The function's name, as Go spells it.
    pub fn name(&self, function: &GoFunction) -> Result<Arc<str>> {
        self.string(&self.funcnametab, function.name as usize)
    }

    /// The name of a function the compiler inlined.
    pub fn inlined_name(&self, call: &InlinedCall) -> Result<Arc<str>> {
        self.string(&self.funcnametab, call.name as usize)
    }

    /// The runs of the pc-value table at `offset`, over one function.
    fn runs(&self, function: &GoFunction, offset: u32) -> Option<PcRuns<'_>> {
        if offset == 0 {
            return None;
        }
        Some(PcRuns {
            data: self.data[self.pctab.clone()].get(offset as usize..)?,
            offset: 0,
            pc: function.entry,
            entry: function.entry,
            value: -1,
            quantum: self.quantum,
            done: false,
        })
    }

    /// The value a pc-value table holds at an address, or `None` when the
    /// function has no such table or the table does not reach the address.
    fn value_at(&self, function: &GoFunction, offset: u32, address: u64) -> Result<Option<i32>> {
        let Some(runs) = self.runs(function, offset) else {
            return if offset == 0 {
                Ok(None)
            } else {
                Err(malformed("a pc-value table is outside the table"))
            };
        };
        for run in runs {
            let run = run?;
            if run.start >= function.end {
                break;
            }
            if address < run.end {
                return Ok((run.start <= address).then_some(run.value));
            }
        }
        Ok(None)
    }

    /// The stack-pointer runs of a function: how far SP is below its value
    /// at entry, through the function.
    pub fn sp_runs(&self, function: &GoFunction) -> Option<PcRuns<'_>> {
        self.runs(function, function.pcsp)
    }

    /// How far SP is below its value at the function's entry, at an address
    /// within the function.
    pub fn sp_delta(&self, function: &GoFunction, address: u64) -> Result<Option<i32>> {
        self.value_at(function, function.pcsp, address)
    }

    /// The source file a file index names in the function's compile unit.
    fn file(&self, function: &GoFunction, index: i32) -> Result<Option<Arc<str>>> {
        let Ok(index) = u32::try_from(index) else {
            return Ok(None);
        };
        let slot = function
            .cu_offset
            .checked_add(index)
            .and_then(|slot| usize::try_from(slot).ok())
            .and_then(|slot| slot.checked_mul(4))
            .and_then(|offset| read_u32(&self.data[self.cutab.clone()], offset))
            .ok_or_else(|| malformed("a file index is outside the compile-unit table"))?;
        if slot == u32::MAX {
            return Ok(None);
        }
        self.string(&self.filetab, slot as usize).map(Some)
    }

    /// The innermost source position of each run of a function's code:
    /// inlined code is attributed to the function it came from.
    pub fn positions(&self, function: &GoFunction) -> Result<Vec<(Range<u64>, GoPosition)>> {
        let (Some(files), Some(lines)) = (
            self.runs(function, function.pcfile),
            self.runs(function, function.pcln),
        ) else {
            return Ok(Vec::new());
        };
        let files = clipped(files, function)?;
        let lines = clipped(lines, function)?;
        let mut positions: Vec<(Range<u64>, GoPosition)> = Vec::new();
        let mut file_names = Vec::<(i32, Option<Arc<str>>)>::new();
        let (mut file, mut line) = (files.iter().peekable(), lines.iter().peekable());
        let mut pc = function.entry;
        while let (Some(file_run), Some(line_run)) = (file.peek(), line.peek()) {
            let end = file_run.end.min(line_run.end);
            let name = if let Some((_, name)) = file_names
                .iter()
                .find(|(index, _)| *index == file_run.value)
            {
                name.clone()
            } else {
                let name = self.file(function, file_run.value)?;
                file_names.push((file_run.value, name.clone()));
                name
            };
            if let Some(name) = name
                && line_run.value > 0
                && pc < end
            {
                let position = GoPosition {
                    file: name,
                    line: line_run.value,
                };
                match positions.last_mut() {
                    Some((range, last)) if range.end == pc && *last == position => range.end = end,
                    _ => positions.push((pc..end, position)),
                }
            }
            pc = end;
            if file_run.end == end {
                file.next();
            }
            if line_run.end == end {
                line.next();
            }
        }
        Ok(positions)
    }

    /// The innermost source position of one address.
    pub fn position(&self, function: &GoFunction, address: u64) -> Result<Option<GoPosition>> {
        let (Some(file), Some(line)) = (
            self.value_at(function, function.pcfile, address)?,
            self.value_at(function, function.pcln, address)?,
        ) else {
            return Ok(None);
        };
        Ok(self
            .file(function, file)?
            .map(|file| GoPosition { file, line }))
    }

    /// The inline-tree runs of a function: the index of the innermost
    /// inlined call at each address, or -1 outside inlined code.
    pub fn inline_runs(&self, function: &GoFunction) -> Result<Vec<PcRun>> {
        if function.npcdata as usize <= PCDATA_INLINE_TREE_INDEX {
            return Ok(Vec::new());
        }
        let offset = read_u32(&self.data, function.pcdata + 4 * PCDATA_INLINE_TREE_INDEX)
            .expect("the record's pcdata is in bounds");
        match self.runs(function, offset) {
            Some(runs) => clipped(runs, function),
            None if offset == 0 => Ok(Vec::new()),
            None => Err(malformed("a pc-value table is outside the table")),
        }
    }

    /// One entry of a function's inline tree.
    pub fn inlined_call(&self, function: &GoFunction, index: i32) -> Result<InlinedCall> {
        if function.nfuncdata as usize <= FUNCDATA_INLINE_TREE {
            return Err(malformed("an inline-tree index names no inline tree"));
        }
        let tree = read_u32(
            &self.data,
            function.pcdata + 4 * (function.npcdata as usize + FUNCDATA_INLINE_TREE),
        )
        .expect("the record's funcdata is in bounds");
        if tree == u32::MAX {
            return Err(malformed("an inline-tree index names no inline tree"));
        }
        let gofunc = self
            .gofunc
            .ok_or_else(|| malformed("the inline trees' base address is unknown"))?;
        let record = usize::try_from(index)
            .ok()
            .and_then(|index| index.checked_mul(INLINED_CALL_SIZE))
            .and_then(|offset| offset.checked_add(gofunc)?.checked_add(tree as usize))
            .and_then(|start| self.data.get(start..start.checked_add(INLINED_CALL_SIZE)?))
            .ok_or(PclntabError::Truncated("an inline tree"))?;
        let field = |index: usize| read_u32(record, 4 * index).expect("the entry is in bounds");
        let name = field(1);
        if name as usize >= self.funcnametab.len() {
            return Err(malformed(
                "an inlined function's name is outside the name table",
            ));
        }
        let parent_pc = function
            .entry
            .checked_add_signed(i64::from(field(2).cast_signed()))
            .filter(|parent| function.contains(*parent))
            .ok_or_else(|| malformed("an inlined call's site is outside its function"))?;
        Ok(InlinedCall {
            special: self
                .numbering
                .and_then(|numbering| numbering.special(record[0])),
            name,
            parent_pc,
            start_line: field(3).cast_signed(),
        })
    }
}

/// What a function's prologue does, by its stack table and the prologue the
/// Go assembler writes (`cmd/internal/obj/x86/obj6.go`): after the stack
/// check, `PUSHQ BP; MOVQ SP, BP`, then `SUBQ $locals, SP` (`ADDQ` for
/// exactly 128 bytes) when the frame has locals. Each epilogue undoes it
/// before `RET`.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Prologue {
    /// Where the caller's frame pointer is in the word below the return
    /// address, wherever SP is at least 8 below its value at entry: from
    /// the push that is the function's first change to SP, which is how
    /// the assembler saves it. Compiled code never pops it but in an
    /// epilogue, where SP returns to its entry value; assembly may, so
    /// there the range ends where SP first returns to its entry value.
    pub frame_pointer_saved: Option<Range<u64>>,
    /// Where Go's DWARF marks the prologue's end, at its last instruction:
    /// the one allocating locals or, without locals, `MOVQ SP, BP`. Only
    /// for compiled code, since assembly may set up its frame by hand.
    pub end: Option<u64>,
}

impl GoTable {
    /// Analyzes a function's prologue. `code` returns the image's code bytes
    /// at an address.
    pub fn prologue<'code>(
        &self,
        function: &GoFunction,
        code: impl Fn(u64, usize) -> Option<&'code [u8]>,
    ) -> Result<Prologue> {
        let Some(runs) = self.sp_runs(function) else {
            return Ok(Prologue::default());
        };
        let runs = clipped(runs, function)?;
        let Some(first) = runs.iter().position(|run| run.value != 0) else {
            return Ok(Prologue::default());
        };
        let pushed = &runs[first];
        let saved = pushed.value == 8
            && pushed.start > function.entry
            && code(pushed.start - 1, 1) == Some(&[0x55][..])
            && code(pushed.start, 3) == Some(&[0x48, 0x89, 0xe5][..]);
        if !saved {
            return Ok(Prologue::default());
        }
        let assembly = function.facts.assembly;
        let saved_until = if assembly {
            runs[first..]
                .iter()
                .find(|run| run.value == 0)
                .map_or(function.end, |run| run.start)
        } else {
            function.end
        };
        let framed = pushed.start + 3;
        let allocates_locals = runs.get(first + 1).is_some_and(|locals| {
            locals.start == pushed.end
                && locals.value > 8
                && locals
                    .start
                    .checked_sub(framed)
                    .and_then(|length| code(framed, usize::try_from(length).ok()?))
                    .is_some_and(allocates_stack)
        });
        Ok(Prologue {
            frame_pointer_saved: Some(pushed.start..saved_until),
            end: (!assembly).then_some(if allocates_locals {
                framed
            } else {
                pushed.start
            }),
        })
    }
}

/// Whether bytes are exactly one `sub $imm, %rsp` or `add $-imm, %rsp`.
const fn allocates_stack(bytes: &[u8]) -> bool {
    matches!(
        bytes,
        [0x48, 0x83, 0xec | 0xc4, _] | [0x48, 0x81, 0xec | 0xc4, _, _, _, _]
    )
}

/// Collects a function's runs, ending them at the function's end.
fn clipped(runs: PcRuns<'_>, function: &GoFunction) -> Result<Vec<PcRun>> {
    let mut clipped = Vec::new();
    for run in runs {
        let run = run?;
        if run.start >= function.end {
            break;
        }
        if run.start < run.end {
            clipped.push(PcRun {
                end: run.end.min(function.end),
                ..run
            });
        }
    }
    Ok(clipped)
}

/// Checks the table's magic number, refusing the formats of other releases
/// by name.
fn check_magic(data: &[u8]) -> Result<()> {
    let magic = read_u32(data, 0).ok_or(PclntabError::Truncated("the header"))?;
    match magic {
        GO120_MAGIC => Ok(()),
        0xffff_fffb => Err(PclntabError::UnsupportedRelease("Go 1.2 through 1.15")),
        0xffff_fffa => Err(PclntabError::UnsupportedRelease("Go 1.16 and 1.17")),
        0xffff_fff0 => Err(PclntabError::UnsupportedRelease("Go 1.18 and 1.19")),
        _ if magic.swap_bytes() == GO120_MAGIC => Err(PclntabError::UnsupportedRelease(
            "a toolchain for a big-endian target",
        )),
        _ => Err(PclntabError::UnknownMagic(magic)),
    }
}

/// Where an image holds its table.
struct FoundTable<'data> {
    address: u64,
    data: &'data [u8],
    /// The end of the section the table was named by, which the linker's
    /// `runtime.epclntab` marks too.
    section_end: Option<u64>,
}

/// Finds and parses an image's Go function table. An image without one,
/// which no Go toolchain linked, has `None`.
pub fn load(object: &object::File<'_>) -> Result<Option<GoTable>> {
    let Some(found) = find_table(object)? else {
        return Ok(None);
    };
    check_magic(found.data)?;
    let header = |index: usize| read_u64(found.data, 8 + 8 * index);
    let module = ModuleWords::new(object).find_moduledata(&found, header);
    // Without the module data, the linker's own marker symbol says where
    // text starts; a stripped image has neither, and its table is unusable.
    let text = module
        .as_ref()
        .map(|module| module.text)
        .or_else(|| symbol_address(object, "runtime.text"))
        .ok_or(PclntabError::TextStartUnknown)?;
    let table = GoTable::parse(
        found.data.into(),
        found.address,
        text,
        module.and_then(|module| module.gofunc),
        go_release(object),
    )?;
    let code = super::elf::executable_ranges(object);
    let within_code = |function: &GoFunction| {
        code.iter()
            .any(|range| range.start.get() <= function.entry && function.end <= range.end.get())
    };
    if !table.functions().iter().all(within_code) {
        return Err(malformed("functions lie outside the image's code"));
    }
    Ok(Some(table))
}

/// Finds the table by its section, which Go names `.gopclntab` (or
/// `.data.rel.ro.gopclntab` for position-independent images before Go
/// 1.26). When a linker merged that section away, a Go image is searched
/// for the table's header.
fn find_table<'data>(object: &object::File<'data>) -> Result<Option<FoundTable<'data>>> {
    use object::{Object, ObjectSection};

    for name in [".gopclntab", ".data.rel.ro.gopclntab"] {
        if let Some(section) = object.section_by_name(name) {
            let data = section.data().map_err(|error| {
                malformed(format!("the table's section is unreadable: {error}"))
            })?;
            return Ok(Some(FoundTable {
                address: section.address(),
                data,
                section_end: section.address().checked_add(section.size()),
            }));
        }
    }
    // Every executable Go links records its build in this section.
    if object.section_by_name(".go.buildinfo").is_none() {
        return Ok(None);
    }
    for section in object.sections() {
        let object::SectionFlags::Elf { sh_flags } = section.flags() else {
            continue;
        };
        let allocated = u64::from(object::elf::SHF_ALLOC);
        let executable = u64::from(object::elf::SHF_EXECINSTR);
        if sh_flags & (allocated | executable) != allocated {
            continue;
        }
        let Ok(data) = section.data() else {
            continue;
        };
        let start = section.address();
        for offset in (aligned_offset(start)..data.len()).step_by(8) {
            let candidate = &data[offset..];
            if let Some(address) = start.checked_add(offset as u64)
                && plausible_header(candidate)
            {
                return Ok(Some(FoundTable {
                    address,
                    data: candidate,
                    section_end: None,
                }));
            }
        }
    }
    Ok(None)
}

/// The offset of the first 8-byte-aligned address at or after `start`.
const fn aligned_offset(start: u64) -> usize {
    ((8 - start % 8) % 8) as usize
}

/// Whether bytes begin with this format's header, whose tables lie in
/// order within the bytes.
fn plausible_header(data: &[u8]) -> bool {
    if read_u32(data, 0) != Some(GO120_MAGIC)
        || data
            .get(4..8)
            .is_none_or(|bytes| bytes[..2] != [0, 0] || bytes[3] != 8)
    {
        return false;
    }
    let words = (3..8)
        .map(|index| read_u64(data, 8 + 8 * index))
        .collect::<Option<Vec<_>>>();
    words.is_some_and(|words| {
        words[0] >= HEADER_SIZE as u64
            && words.windows(2).all(|pair| pair[0] <= pair[1])
            && words[4] <= data.len() as u64
    })
}

/// The address of a static symbol, when the image keeps its symbol table.
fn symbol_address(object: &object::File<'_>, name: &str) -> Option<u64> {
    use object::{Object, ObjectSymbol};

    object
        .symbols()
        .find(|symbol| symbol.name_bytes().ok() == Some(name.as_bytes()))
        .map(|symbol| symbol.address())
}

/// The fields of `runtime.moduledata` the table needs.
struct ModuleData {
    text: u64,
    gofunc: Option<u64>,
}

/// The image's writable data, as the words it holds once loaded: a word a
/// relative relocation sets holds the relocation's addend.
struct ModuleWords<'data> {
    sections: Vec<(u64, &'data [u8])>,
    relative: std::collections::BTreeMap<u64, u64>,
}

/// Word indexes of the `runtime.moduledata` fields that locate it, which
/// Go 1.20 through 1.27 lay out alike: `pcHeader`, then the six table
/// slices (`funcnametab`, `cutab`, `filetab`, `pctab`, `pclntable`,
/// `ftab`), `findfunctab`, `minpc`, `maxpc`, `text`, and `etext`.
const MODULE_PC_HEADER: u64 = 0;
const MODULE_FUNCNAMETAB: u64 = 1;
const MODULE_FTAB: u64 = 16;
const MODULE_FTAB_LENGTH: u64 = 17;
const MODULE_MINPC: u64 = 20;
const MODULE_TEXT: u64 = 22;
/// The fields after `etext` move between releases; `gofunc` is always the
/// word before `epclntab`, which is the end of the table's section.
const MODULE_LATER_FIELDS: Range<u64> = 24..96;

impl<'data> ModuleWords<'data> {
    fn new(object: &object::File<'data>) -> Self {
        use object::{Object, ObjectSection};

        let writable = u64::from(object::elf::SHF_ALLOC | object::elf::SHF_WRITE);
        let sections = object
            .sections()
            .filter(|section| {
                matches!(section.flags(), object::SectionFlags::Elf { sh_flags }
                    if sh_flags & writable == writable)
            })
            .filter_map(|section| Some((section.address(), section.data().ok()?)))
            .collect();
        let relative = object
            .dynamic_relocations()
            .into_iter()
            .flatten()
            .filter(|(_, relocation)| {
                matches!(relocation.flags(), object::RelocationFlags::Elf { r_type }
                    if r_type == object::elf::R_X86_64_RELATIVE)
            })
            .filter_map(|(address, relocation)| {
                Some((address, u64::try_from(relocation.addend()).ok()?))
            })
            .collect();
        Self { sections, relative }
    }

    fn word(&self, address: u64) -> Option<u64> {
        if let Some(value) = self.relative.get(&address) {
            return Some(*value);
        }
        let (start, data) = self
            .sections
            .iter()
            .find(|(start, data)| *start <= address && address - start < data.len() as u64)?;
        read_u64(data, usize::try_from(address - start).ok()?)
    }

    /// Finds the module data that points at the table, and checks it
    /// against the table's header before trusting its text start.
    fn find_moduledata(
        &self,
        found: &FoundTable<'_>,
        header: impl Fn(usize) -> Option<u64>,
    ) -> Option<ModuleData> {
        let table = found.address;
        let nfunc = header(0)?;
        let funcnametab = table.checked_add(header(3)?)?;
        let ftab = table.checked_add(header(7)?)?;
        let first_entry = u64::from(read_u32(found.data, usize::try_from(header(7)?).ok()?)?);
        let mut candidates = self
            .relative
            .iter()
            .filter(|(_, value)| **value == table)
            .map(|(address, _)| *address)
            .collect::<Vec<_>>();
        for (start, data) in &self.sections {
            candidates.extend(
                (aligned_offset(*start)..data.len().saturating_sub(7))
                    .step_by(8)
                    .filter(|offset| read_u64(data, *offset) == Some(table))
                    .filter_map(|offset| start.checked_add(offset as u64)),
            );
        }
        candidates.sort_unstable();
        candidates.dedup();
        candidates.into_iter().find_map(|module| {
            let field = |index: u64| self.word(module.checked_add(8 * index)?);
            let text = field(MODULE_TEXT)?;
            let valid = field(MODULE_PC_HEADER) == Some(table)
                && field(MODULE_FUNCNAMETAB) == Some(funcnametab)
                && field(MODULE_FTAB) == Some(ftab)
                && field(MODULE_FTAB_LENGTH) == nfunc.checked_add(1)
                && field(MODULE_MINPC) == text.checked_add(first_entry);
            valid.then(|| ModuleData {
                text,
                gofunc: found.section_end.and_then(|end| {
                    MODULE_LATER_FIELDS
                        .filter(|index| field(*index) == Some(end))
                        .find_map(|index| field(index - 1))
                        .filter(|gofunc| (table..end).contains(gofunc))
                }),
            })
        })
    }
}

/// The Go release that built an image, from its build information.
fn go_release(object: &object::File<'_>) -> Option<GoRelease> {
    use object::{Object, ObjectSection};

    let section = object.section_by_name(".go.buildinfo")?;
    let data = section.data().ok()?;
    // From Go 1.18 the header's flags say the version follows it inline,
    // as a varint length and the bytes.
    if data.get(..14)? != b"\xff Go buildinf:" || data.get(15)? & 2 == 0 {
        return None;
    }
    let mut offset = 32;
    let length = read_varint(data, &mut offset).ok()? as usize;
    let version = data.get(offset..offset.checked_add(length)?)?;
    GoRelease::parse(std::str::from_utf8(version).ok()?)
}

/// Exercises the table reader on arbitrary bytes, for the fuzz harness: as
/// an ELF image to locate the table in, or as a table itself.
#[cfg(feature = "fuzzing")]
pub fn fuzz(data: &[u8]) {
    if data.starts_with(b"\x7fELF") {
        if let Ok(object) = object::File::parse(data)
            && let Ok(Some(table)) = load(&object)
        {
            fuzz_table(&table, data);
        }
        return;
    }
    let mut bytes = data.to_vec();
    // Most inputs should reach past the magic number.
    if bytes.len() >= 8 && bytes[0] & 1 == 0 {
        bytes[..8].copy_from_slice(&[0xf1, 0xff, 0xff, 0xff, 0, 0, 1, 8]);
    }
    let gofunc = bytes
        .get(8..16)
        .map(|word| 0x1000 + u64::from_le_bytes(word.try_into().expect("eight bytes")) % 0x1_0000);
    let release = Some(GoRelease {
        major: 1,
        minor: 27,
    });
    if let Ok(table) = GoTable::parse(bytes.into(), 0x1000, 0x40_0000, gofunc, release) {
        fuzz_table(&table, data);
    }
}

/// Decodes everything a table holds, checking what every decoding promises.
/// `code` stands in for the image's code bytes.
#[cfg(feature = "fuzzing")]
fn fuzz_table(table: &GoTable, code: &[u8]) {
    let code = |address: u64, length: usize| {
        let start = usize::try_from(address % 0x1_0000).ok()?;
        code.get(start..start.checked_add(length)?)
    };
    for function in table.functions() {
        assert!(function.entry <= function.end);
        let _ = table.name(function);
        if let Some(runs) = table.sp_runs(function) {
            for run in runs.take(4096) {
                let Ok(run) = run else { break };
                assert!(run.start <= run.end);
            }
        }
        let _ = table.sp_delta(function, function.entry);
        if let Ok(prologue) = table.prologue(function, code) {
            assert!(prologue.end.is_none_or(|end| function.contains(end)));
        }
        if let Ok(positions) = table.positions(function) {
            for (range, _) in positions {
                assert!(function.entry <= range.start);
                assert!(range.end <= function.end);
            }
        }
        let _ = table.position(function, function.end.saturating_sub(1));
        if let Ok(runs) = table.inline_runs(function) {
            for run in runs.iter().filter(|run| run.value >= 0) {
                if let Ok(call) = table.inlined_call(function, run.value) {
                    assert!(function.contains(call.parent_pc));
                    let _ = table.inlined_name(&call);
                }
            }
        }
        assert!(
            function.entry == function.end
                || table
                    .function_containing(function.entry)
                    .is_some_and(|found| found.contains(function.entry))
        );
    }

    let (mut functions, mut instances) = (Vec::new(), Vec::new());
    let mut lines = crate::image::lines::LineTables::default();
    let mut files = crate::image::lines::Files::default();
    let completed = {
        let mut catalog = Catalog {
            functions: &mut functions,
            code_instances: &mut instances,
            lines: &mut lines,
            source_file: &mut |path| files.intern(path),
        };
        complete_metadata(table, code, &mut catalog).is_ok()
    };
    if completed {
        for (index, instance) in instances.iter().enumerate() {
            assert_eq!(instance.id.index(), index);
            assert!(instance.function.index() < functions.len());
            assert!(
                instance
                    .parent
                    .is_none_or(|parent| parent.index() < instances.len())
            );
            assert!(instance.ranges.iter().all(|range| range.start < range.end));
        }
        // The line tables are valid: they seal into an image.
        let mut image = crate::image::Builder::new(crate::TargetDescription::X86_64);
        lines.add_to(&mut image);
        let mut paths = crate::image::PathsBuilder::default();
        files
            .add_to(&mut image, &mut paths)
            .expect("paths without NULs");
        image.bytes(crate::image::TableKind::Paths, paths.into_bytes());
        image
            .seal(crate::image::Limits::default())
            .expect("the completed line tables are valid");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture(name: &str) -> Vec<u8> {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("build/test-programs")
            .join(name);
        std::fs::read(&path).unwrap_or_else(|error| {
            panic!(
                "missing {}: {error}; run `just build-test-programs`",
                path.display()
            )
        })
    }

    /// The table matches Go's own `debug/gosym` exactly: every function's
    /// name, entry, and end, and the position of sampled addresses, in an
    /// image with symbols and one without.
    #[test]
    fn the_reader_agrees_with_go_debug_gosym() {
        for name in ["callers-go", "callers-go-stripped"] {
            let bytes = fixture(name);
            let object = object::File::parse(bytes.as_slice()).expect("parse the fixture");
            let table = load(&object)
                .expect("read the function table")
                .expect("a Go image has a function table");
            let oracle = String::from_utf8(fixture(&format!("{name}.gosym"))).expect("text");
            let mut lines = oracle.lines();
            assert_eq!(lines.next(), Some("uscope-gosym-oracle-v1"));
            let hex = |field: &str| {
                u64::from_str_radix(field.trim_start_matches("0x"), 16).expect("hex address")
            };
            let mut functions = Vec::new();
            let mut positions = 0;
            for line in lines {
                match line.split('\t').collect::<Vec<_>>().as_slice() {
                    ["func", entry, end, function] => {
                        functions.push((hex(entry), hex(end), (*function).to_owned()));
                    }
                    ["line", pc, file, line] => {
                        let pc = hex(pc);
                        let function = table.function_containing(pc).expect("a sampled function");
                        let expected = (!file.is_empty()).then(|| GoPosition {
                            file: (*file).into(),
                            line: line.parse().expect("line number"),
                        });
                        assert_eq!(
                            table.position(function, pc).expect("read the position"),
                            expected,
                            "{name}: {pc:#x}"
                        );
                        positions += 1;
                    }
                    other => panic!("unknown oracle line {other:?}"),
                }
            }
            let read = table
                .functions()
                .iter()
                .map(|function| {
                    let name = table.name(function).expect("a name");
                    (function.entry, function.end, name.to_string())
                })
                .collect::<Vec<_>>();
            assert_eq!(read, functions, "{name}");
            assert!(functions.len() > 1000 && positions > 3000, "{name}");
        }
    }

    /// Where the stack table and the code place a compiled function's
    /// prologue end is where Go's own DWARF marks it, in optimized and
    /// unoptimized code alike.
    #[test]
    fn prologue_ends_agree_with_go_dwarf() {
        use object::{Object, ObjectSection};

        for name in ["callers-go", "crash-go-o0"] {
            let bytes = fixture(name);
            let object = object::File::parse(bytes.as_slice()).expect("parse the fixture");
            let table = load(&object).expect("read the table").expect("a table");
            let text = object.section_by_name(".text").expect("a text section");
            let code_bytes = text.data().expect("text bytes");
            let code = |address: u64, length: usize| {
                let start = usize::try_from(address.checked_sub(text.address())?).ok()?;
                code_bytes.get(start..start.checked_add(length)?)
            };
            let image = crate::debug_info::load_program(
                std::path::Path::new(name),
                &bytes,
                &crate::debug_info::DebugFileSearch::default(),
            )
            .expect("load the fixture's DWARF")
            .image;
            let mut compared = 0;
            for instance in image
                .code_instances()
                .filter(|instance| matches!(instance.kind(), crate::CodeInstanceKind::OutOfLine))
            {
                let entry = instance.ranges().next().expect("a range").start.get();
                let Some(function) = table
                    .function_containing(entry)
                    .filter(|function| function.entry == entry && !function.facts.assembly)
                else {
                    continue;
                };
                let marked = image
                    .recommended_entries_for_instance(instance.id())
                    .filter(|entry| entry.provenance == crate::EntryProvenance::Statement)
                    .map(|entry| entry.address.get())
                    .collect::<Vec<_>>();
                let derived = table.prologue(function, code).expect("a prologue").end;
                assert_eq!(
                    marked,
                    derived.into_iter().collect::<Vec<_>>(),
                    "{name}: {}",
                    table.name(function).expect("a name")
                );
                compared += 1;
            }
            assert!(compared > 1000, "{name}: {compared}");
        }
    }
}
