//! The roles code plays in unwinding and stepping, decided once from what
//! the debug information and symbol tables name. Nothing else in uscope
//! recognizes code by its name.

use super::gopclntab::{GoFunctionFacts, SpecialFunction};
use crate::CodeRole;

/// The role of code that only a linker symbol describes.
pub fn symbol_role(name: &str) -> CodeRole {
    match name {
        // The process's entry point, which nothing calls.
        "_start" => CodeRole::Outermost,
        // glibc's `sa_restorer`, which a signal handler returns to.
        "__restore_rt" => CodeRole::SignalTrampoline,
        _ => CodeRole::Ordinary,
    }
}

/// The role of a function Go compiled or assembled, following the runtime's
/// own traceback (`runtime/traceback.go`). `facts` are the function table's
/// record of the function, when it has one and the image's release numbers
/// function IDs in a way written down; `generated` says the debug
/// information marks it a trampoline or declares it in `<autogenerated>`.
///
/// When several roles apply, the first of these wins, each because it
/// governs how unwinding treats the frame:
///
/// 1. `SignalTrampoline`: `runtime.sigreturn__sigaction`, Go's
///    `sa_restorer`.
/// 2. `TrapEntry`: `sigpanic`, `asyncPreempt`, and `debugCallV2`, which the
///    runtime injects; their caller's pc is exact.
/// 3. `Outermost`: functions flagged `TOPFRAME` (`goexit`, `mstart`,
///    `rt0_go`, which also writes SP). The signal handlers `sigtramp` and
///    `cgoSigtramp` are flagged too, but the kernel calls them with the
///    signal trampoline as their return address, so unwinding goes on
///    through the signal frame; they fall to the rules below.
/// 4. `StackSwitch`: functions flagged `SPWRITE`, and the stack switches
///    the runtime knows by ID (`systemstack`, `mcall`, `morestack`,
///    `asmcgocall`, `cgocallback`).
/// 5. `Wrapper`: autogenerated code (the `Wrapper` function ID, which ABI
///    wrappers carry and their real functions do not), and code the debug
///    information marks generated.
/// 6. `RuntimeInternal`: what the runtime's traceback hides, that is a
///    `runtime.` function or method that is not exported, or a name with no
///    package, and anything under `internal/runtime/` or
///    `runtime/internal/`.
/// 7. `Ordinary`: everything else.
pub fn go_role(name: &str, facts: Option<GoFunctionFacts>, generated: bool) -> CodeRole {
    let special = facts.and_then(|facts| facts.special);
    if name == "runtime.sigreturn__sigaction" {
        return CodeRole::SignalTrampoline;
    }
    if matches!(
        special,
        Some(
            SpecialFunction::Sigpanic
                | SpecialFunction::AsyncPreempt
                | SpecialFunction::DebugCallV2
        )
    ) {
        return CodeRole::TrapEntry;
    }
    let signal_handler = matches!(name, "runtime.sigtramp" | "runtime.cgoSigtramp");
    if facts.is_some_and(|facts| facts.top_frame) && !signal_handler {
        return CodeRole::Outermost;
    }
    if facts.is_some_and(|facts| facts.sp_write)
        || matches!(
            special,
            Some(
                SpecialFunction::Systemstack
                    | SpecialFunction::Mcall
                    | SpecialFunction::Morestack
                    | SpecialFunction::AsmCgoCall
                    | SpecialFunction::CgoCallback
            )
        )
    {
        return CodeRole::StackSwitch;
    }
    if special == Some(SpecialFunction::Wrapper) || generated {
        return CodeRole::Wrapper;
    }
    if is_runtime_internal(name) {
        return CodeRole::RuntimeInternal;
    }
    CodeRole::Ordinary
}

/// Whether a Go function belongs to the runtime's own machinery.
fn is_runtime_internal(name: &str) -> bool {
    if name.starts_with("internal/runtime/") || name.starts_with("runtime/internal/") {
        return true;
    }
    // The runtime's assembly helpers, such as `gogo`, have no package.
    if !name.contains('.') {
        return true;
    }
    name.strip_prefix("runtime.")
        .is_some_and(|rest| !is_exported_runtime(rest))
}

/// Whether a runtime function, named without its `runtime.` prefix, is
/// exported: an exported function, or an exported method of an exported
/// type (`isExportedRuntime`).
fn is_exported_runtime(name: &str) -> bool {
    let (receiver, function) = name.rsplit_once('.').unwrap_or(("", name));
    let receiver = receiver
        .strip_prefix("(*")
        .and_then(|receiver| receiver.strip_suffix(')'))
        .unwrap_or(receiver);
    let exported = |text: &str| text.starts_with(|first: char| first.is_ascii_uppercase());
    exported(function) && (receiver.is_empty() || exported(receiver))
}
