//! The roles code plays in unwinding and stepping, decided once from what
//! the debug information and symbol tables name. Nothing else in uscope
//! recognizes code by its name.

use std::collections::BTreeSet;

use super::gopclntab::{GoFunctionFacts, SpecialFunction};
use std::path::PathBuf;

use crate::{CodeRole, FunctionInfo, SourceLanguage};

/// The file Go declares the code it generates in: wrappers, but also
/// package initializers and equality functions, which do work of their own.
const AUTOGENERATED: &str = "<autogenerated>";

/// The files cgo writes the code it generates into: the Go that calls C
/// and that C calls back, the C that Go's calls enter, and the C that calls
/// exported Go functions. The program's own C, in a Go file's preamble or a
/// C file of its package, is declared where its author wrote it.
const CGO_GENERATED: [&str; 3] = ["_cgo_gotypes.go", "cgo-gcc-prolog", "_cgo_export.c"];

/// Whether code declared in `path` is cgo's, which passes calls between Go
/// and C and is no more the program's own than an ABI wrapper is.
pub fn cgo_wrote(path: &std::path::Path) -> bool {
    path.file_name()
        .and_then(|name| name.to_str())
        .is_some_and(|name| CGO_GENERATED.contains(&name))
}

/// Which functions cgo generated, in Go or in C: those declared in a file
/// it writes.
pub fn cgo_generated(functions: &[FunctionInfo], source_files: &[PathBuf]) -> Vec<bool> {
    declared_in(functions, source_files, cgo_wrote)
}

/// Which functions are the C the Go runtime links into a program that
/// uses cgo, such as the code that starts its threads: those declared in
/// `runtime/cgo` of Go's source tree. They are the runtime's own machinery
/// as much as its Go is.
pub fn cgo_runtime(functions: &[FunctionInfo], source_files: &[PathBuf]) -> Vec<bool> {
    declared_in(functions, source_files, |path| {
        path.parent()
            .is_some_and(|directory| directory.ends_with("src/runtime/cgo"))
    })
}

fn declared_in(
    functions: &[FunctionInfo],
    source_files: &[PathBuf],
    file: impl Fn(&std::path::Path) -> bool,
) -> Vec<bool> {
    // Each file once, rather than once for each function it declares.
    let in_file = source_files
        .iter()
        .map(|path| file(path))
        .collect::<Vec<_>>();
    functions
        .iter()
        .map(|function| {
            function
                .declaration
                .as_ref()
                .and_then(|location| in_file.get(location.file.index()))
                .is_some_and(|within| *within)
        })
        .collect()
}

/// The role of a function its debug information describes: a wrapper when
/// its DIE says it is a trampoline.
pub fn function_role(name: &str, trampoline: bool) -> CodeRole {
    if trampoline {
        return CodeRole::Wrapper;
    }
    symbol_role(name)
}

/// The role of a Rust function, by the path of namespaces rustc nests it
/// in, outermost first and joined by `::`, and its own name, or `None` for
/// an ordinary function. The library's code that only hands a future on,
/// which every `.await` runs between the awaiting function and the awaited
/// one, wraps: `IntoFuture`, the rest of `core::future` and `core::pin`,
/// the `poll` that `Box` forwards and the `deref_mut` through which a
/// `Pin<Box<_>>` reaches its future, and `AssertUnwindSafe`. So does the drop
/// glue rustc generates, which calls the `Drop` impls the program wrote and
/// carries the lines of what it drops, such as an await's. std's and core's
/// code that raises a panic is the panic machinery.
///
/// All of tokio is machinery, as Go's runtime is: its runtime, its tasks'
/// harness, the drivers and pools beneath them, and the libraries a
/// program awaits, such as `tokio::sync`, whose frames a task's backtrace
/// folds and a step passes through. So is mio's code, which the drivers
/// call. A task's frames begin where its harness polls it.
pub fn rust_role(namespace: &str, name: &str) -> Option<CodeRole> {
    let within = |path: &str| {
        namespace
            .strip_prefix(path)
            .is_some_and(|rest| rest.is_empty() || rest.starts_with("::"))
    };
    let named = |function: &str| {
        name.strip_prefix(function)
            .is_some_and(|rest| rest.is_empty() || rest.starts_with('<'))
    };
    // std's code that catches a panic, under which a runtime polls its
    // tasks and a thread runs its closure, is machinery like theirs.
    if within("std::panicking::catch_unwind")
        || (within("std::panicking") || within("std::panic")) && named("catch_unwind")
    {
        return Some(CodeRole::RuntimeInternal);
    }
    // std's and core's code that raises a panic, which a step goes
    // through to the `Drop` impls the panic runs as it unwinds.
    if within("core::panicking")
        || within("std::panicking")
        || within("__rustc")
        || (within("std::sys::backtrace") && named("__rust_end_short_backtrace"))
    {
        return Some(CodeRole::Panic);
    }
    // `Harness::poll::<T, S>`, which rustc nests in its type, and which
    // stays a function of its own in every build: optimization inlines
    // what calls it, and the vtable's `raw::poll` only jumps to it.
    if namespace == "tokio::runtime::task::harness" && name.starts_with("poll<") {
        return Some(CodeRole::Dispatch);
    }
    if within("tokio") || within("mio") {
        return Some(CodeRole::RuntimeInternal);
    }
    (within("core::future")
        || within("core::pin")
        || within("core::panic::unwind_safe")
        || (within("alloc::boxed") && (named("poll") || named("deref_mut")))
        || (within("core::ptr") && (named("drop_glue") || named("drop_in_place"))))
    .then_some(CodeRole::Wrapper)
}

/// Which functions are Go's ABI wrappers, which carry no trampoline mark:
/// each shares its function's name, and is declared in Go's generated file
/// while the function is not.
pub fn abi_wrappers(functions: &[FunctionInfo], source_files: &[PathBuf]) -> Vec<bool> {
    let generated = declared_in(functions, source_files, |path| {
        path.file_name().is_some_and(|file| file == AUTOGENERATED)
    });
    if !generated.contains(&true) {
        return generated;
    }
    let written = functions
        .iter()
        .zip(&generated)
        .filter(|(_, generated)| !**generated)
        .map(|(function, _)| &*function.name)
        .collect::<BTreeSet<_>>();
    functions
        .iter()
        .zip(generated)
        .map(|(function, generated)| generated && written.contains(&*function.name))
        .collect()
}

/// Links each loop body a compiler made a function of its own to the
/// function whose loop it is. Go names a range-over-func body after its
/// enclosing function, `F-rangeN`, and a body within a body
/// `F-rangeN-rangeM`. Where an ABI wrapper shares the enclosing function's
/// name, the body belongs to the function, not the wrapper.
pub fn link_loop_bodies(functions: &mut [FunctionInfo]) {
    let mut by_name = std::collections::HashMap::new();
    for function in functions.iter().filter(|function| {
        function.language == SourceLanguage::Go && function.role != CodeRole::Wrapper
    }) {
        by_name.entry(function.name.clone()).or_insert(function.id);
    }
    for function in functions
        .iter_mut()
        .filter(|function| function.language == SourceLanguage::Go)
    {
        function.enclosing = go_loop_parent(&function.name)
            .and_then(|parent| by_name.get(parent))
            .copied();
    }
}

/// The name of the function whose loop a Go range-over-func body is.
fn go_loop_parent(name: &str) -> Option<&str> {
    let (parent, number) = name.rsplit_once("-range")?;
    (!parent.is_empty() && !number.is_empty() && number.bytes().all(|byte| byte.is_ascii_digit()))
        .then_some(parent)
}

/// The role of code that only a linker symbol describes.
pub fn symbol_role(name: &str) -> CodeRole {
    match name {
        // The process's entry point, which nothing calls.
        "_start" => CodeRole::Outermost,
        // glibc's `sa_restorer`, which a signal handler returns to.
        "__restore_rt" => CodeRole::SignalTrampoline,
        // Rust's intrinsic that calls code under `catch_unwind`.
        "__rust_try" => CodeRole::RuntimeInternal,
        _ => CodeRole::Ordinary,
    }
}

/// The role of a function Go compiled or assembled, following the runtime's
/// own traceback (`runtime/traceback.go`). `facts` are the function table's
/// record of the function, when it has one and the image's release numbers
/// function IDs in a way written down; `generated` says the debug
/// information marks it a trampoline or declares it in `<autogenerated>`.
///
/// When several roles apply, the first of these wins, each because it
/// governs how unwinding treats the frame:
///
/// 1. `SignalTrampoline`: `runtime.sigreturn__sigaction`, Go's
///    `sa_restorer`.
/// 2. `TrapEntry`: `sigpanic`, `asyncPreempt`, and `debugCallV2`, which the
///    runtime injects; their caller's pc is exact.
/// 3. `Outermost`: functions flagged `TOPFRAME` (`goexit`, `mstart`,
///    `rt0_go`, which also writes SP). The signal handlers `sigtramp` and
///    `cgoSigtramp` are flagged too, but the kernel calls them with the
///    signal trampoline as their return address, so unwinding goes on
///    through the signal frame; they fall to the rules below.
/// 4. `StackSwitch`: functions flagged `SPWRITE`, and the stack switches
///    the runtime knows by ID (`systemstack`, `mcall`, `morestack`,
///    `asmcgocall`, `cgocallback`).
/// 5. `Wrapper`: autogenerated code (the `Wrapper` function ID, which ABI
///    wrappers carry and their real functions do not, as does
///    `deferreturn`, which calls a function's deferred functions as it
///    returns), code the debug information marks generated, and code cgo
///    generated.
/// 6. `Panic`: `gopanic`, which calls deferred functions as a panic
///    unwinds.
/// 7. `Dispatch`: `execute`, which makes a goroutine the thread's own.
/// 8. `RuntimeInternal`: what the runtime's traceback hides, that is a
///    `runtime.` function or method that is not exported, or a name with no
///    package, and anything under `internal/runtime/` or
///    `runtime/internal/`.
/// 9. `Ordinary`: everything else.
pub fn go_role(name: &str, facts: Option<GoFunctionFacts>, generated: bool) -> CodeRole {
    let special = facts.and_then(|facts| facts.special);
    if name == "runtime.sigreturn__sigaction" {
        return CodeRole::SignalTrampoline;
    }
    if matches!(
        special,
        Some(
            SpecialFunction::Sigpanic
                | SpecialFunction::AsyncPreempt
                | SpecialFunction::DebugCallV2
        )
    ) {
        return CodeRole::TrapEntry;
    }
    let signal_handler = matches!(name, "runtime.sigtramp" | "runtime.cgoSigtramp");
    if facts.is_some_and(|facts| facts.top_frame) && !signal_handler {
        return CodeRole::Outermost;
    }
    if facts.is_some_and(|facts| facts.sp_write)
        || matches!(
            special,
            Some(
                SpecialFunction::Systemstack
                    | SpecialFunction::Mcall
                    | SpecialFunction::Morestack
                    | SpecialFunction::AsmCgoCall
                    | SpecialFunction::CgoCallback
            )
        )
    {
        return CodeRole::StackSwitch;
    }
    if special == Some(SpecialFunction::Wrapper) || generated {
        return CodeRole::Wrapper;
    }
    if name == "runtime.gopanic" {
        return CodeRole::Panic;
    }
    if name == "runtime.execute" {
        return CodeRole::Dispatch;
    }
    if is_runtime_internal(name) {
        return CodeRole::RuntimeInternal;
    }
    CodeRole::Ordinary
}

/// Whether a Go function belongs to the runtime's own machinery.
fn is_runtime_internal(name: &str) -> bool {
    if name.starts_with("internal/runtime/") || name.starts_with("runtime/internal/") {
        return true;
    }
    // The runtime's assembly helpers, such as `gogo`, have no package.
    if !name.contains('.') {
        return true;
    }
    name.strip_prefix("runtime.")
        .is_some_and(|rest| !is_exported_runtime(rest))
}

/// Whether a runtime function, named without its `runtime.` prefix, is
/// exported: an exported function, or an exported method of an exported
/// type (`isExportedRuntime`).
fn is_exported_runtime(name: &str) -> bool {
    let (receiver, function) = name.rsplit_once('.').unwrap_or(("", name));
    let receiver = receiver
        .strip_prefix("(*")
        .and_then(|receiver| receiver.strip_suffix(')'))
        .unwrap_or(receiver);
    let exported = |text: &str| text.starts_with(|first: char| first.is_ascii_uppercase());
    exported(function) && (receiver.is_empty() || exported(receiver))
}
