//! The roles code plays in unwinding and stepping, decided once from what
//! the debug information and symbol tables name. Nothing else in uscope
//! recognizes code by its name.

use std::collections::HashSet;

use crate::{CodeRole, FunctionInfo, SourceFile};

/// The file Go declares the code it generates in: wrappers, but also
/// package initializers and equality functions, which do work of their own.
const AUTOGENERATED: &str = "<autogenerated>";

/// The role of a function its debug information describes: a wrapper when
/// its DIE says it is a trampoline.
pub fn function_role(name: &str, trampoline: bool) -> CodeRole {
    if trampoline {
        return CodeRole::Wrapper;
    }
    symbol_role(name)
}

/// Marks Go's ABI wrappers, which carry no trampoline mark: each shares
/// its function's name, and is declared in Go's generated file while the
/// function is not.
pub fn mark_abi_wrappers(functions: &mut [FunctionInfo], source_files: &[SourceFile]) {
    let generated = |function: &FunctionInfo| {
        function
            .declaration
            .as_ref()
            .and_then(|location| source_files.get(location.file.index()))
            .and_then(|file| file.path.file_name())
            .is_some_and(|file| file == AUTOGENERATED)
    };
    let written = functions
        .iter()
        .filter(|function| !generated(function))
        .map(|function| std::sync::Arc::clone(&function.name))
        .collect::<HashSet<_>>();
    for function in functions {
        if generated(function) && written.contains(&function.name) {
            function.role = CodeRole::Wrapper;
        }
    }
}

/// The role of code that only a linker symbol describes.
pub fn symbol_role(name: &str) -> CodeRole {
    match name {
        // The process's entry point, which nothing calls.
        "_start" => CodeRole::Outermost,
        // glibc's `sa_restorer`, which a signal handler returns to.
        "__restore_rt" => CodeRole::SignalTrampoline,
        _ => CodeRole::Ordinary,
    }
}
