[package]
name = "uscope-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
uscope = { path = "..", features = ["fuzzing"] }

[[bin]]
name = "value-expression"
path = "fuzz_targets/value_expression.rs"
test = false
doc = false
bench = false

[[bin]]
name = "dwarf-expression"
path = "fuzz_targets/dwarf_expression.rs"
test = false
doc = false
bench = false

[[bin]]
name = "core-dump"
path = "fuzz_targets/core_dump.rs"
test = false
doc = false
bench = false

[[bin]]
name = "debug-register-plan"
path = "fuzz_targets/debug_register_plan.rs"
test = false
doc = false
bench = false

[[bin]]
name = "elf-symbols"
path = "fuzz_targets/elf_symbols.rs"
test = false
doc = false
bench = false
